//! Single-origin SPA static serving for the Warden Console (ADR 221 §D5).
//!
//! SECURITY-LANE. This serves the built SvelteKit dashboard
//! (`crates/emberlink-gui/build/`) from the daemon's own Hyper handler at
//! `127.0.0.1:3141`, the SAME origin as the authority API, reusing the existing
//! loopback-bind + CSRF + Origin gate (there is no separate static origin). The
//! assets are embedded at COMPILE time by `build.rs` into `SPA_ASSETS`
//! (`include_bytes!` table), so:
//!
//!   * the SPA travels inside the signed binary (integrity rides codesigning),
//!   * serving is purely an in-memory table lookup by EXACT url path — there is
//!     no runtime filesystem read and therefore no path-traversal surface, and
//!   * when no SPA is embedded (fresh checkout / CI without a frontend build)
//!     `SPA_ASSETS` is empty and the daemon keeps serving its legacy dashboard.
//!
//! GETs are not CSRF-gated in the dashboard's design (only POSTs check
//! `origin_ok`/`csrf_ok`); the loopback bind already restricts callers to
//! `127.0.0.1`. The only secret on these GET responses is the per-process CSRF
//! token templated into `index.html`.
//!
//! ## Token-bearing document is bounded and uncacheable (adversarial review)
//!
//! The CSRF-token-bearing `index.html` is served on EXACTLY two paths (`/` and
//! `/index.html`) — never an open-ended client-route fallback — so the token's
//! response surface matches the legacy single-document `DASHBOARD_HTML` and no
//! `/metrics/`-style variant of another route can fall through to it. It is sent
//! `Cache-Control: no-store` with NO ETag, so a same-binary daemon restart
//! (which mints a fresh per-process CSRF token) can never serve a 304 that
//! strands a stale token in a browser cache. Every other path is an EXACT asset
//! lookup or a 404; there is no extensionless fallback to `index.html`. (The
//! current frontend uses in-memory navigation, so `/` is the only HTML entry
//! point. When URL-deep-linkable client routes land, this fallback must be
//! re-opened against the KNOWN SvelteKit route set emitted from `build.rs`, not
//! a string heuristic.)

use bytes::Bytes;
use http_body_util::Full;
use hyper::{Response, StatusCode};

// @generated by build.rs: `pub static SPA_ASSETS: &[(&str, &[u8], &str)]`.
include!(concat!(env!("OUT_DIR"), "/spa_assets.rs"));

/// The placeholder the daemon replaces with the per-process CSRF token when it
/// serves `index.html` (mirrors the legacy `DASHBOARD_HTML` `{{CSRF_TOKEN}}`
/// substitution). Split via `concat!` so this source line is not itself a
/// literal the frontend's static `index.html` could ever collide with.
const CSRF_PLACEHOLDER: &str = concat!("{{", "CSRF_TOKEN", "}}");

/// True when a built SPA is embedded in this binary.
pub fn is_embedded() -> bool {
    !SPA_ASSETS.is_empty()
}

fn lookup(path: &str) -> Option<(&'static [u8], &'static str)> {
    SPA_ASSETS
        .iter()
        .find(|(p, _, _)| *p == path)
        .map(|(_, bytes, ctype)| (*bytes, *ctype))
}

fn ok_bytes(bytes: &'static [u8], ctype: &str, cache_control: &str) -> Response<Full<Bytes>> {
    Response::builder()
        .status(StatusCode::OK)
        .header("content-type", ctype)
        .header("cache-control", cache_control)
        // Defense in depth: the content-type is from an explicit allowlist, so
        // forbid MIME sniffing rather than let a browser reinterpret an asset.
        .header("x-content-type-options", "nosniff")
        .body(Full::new(Bytes::from_static(bytes)))
        .unwrap()
}

/// Template the per-process CSRF token into the index HTML. Pure (no I/O) so
/// the substitution is unit-testable on its own.
fn render_index(raw: &[u8], csrf: &str) -> String {
    String::from_utf8_lossy(raw).replace(CSRF_PLACEHOLDER, csrf)
}

/// Serve `index.html` with the per-process CSRF token templated in. The token
/// is a secret, so the document is `no-store` (never cached) and carries NO
/// ETag — a fresh daemon process must always deliver its own token, never a
/// 304-revalidated stale one.
fn serve_index(csrf: &str) -> Option<Response<Full<Bytes>>> {
    let (raw, _) = lookup("/index.html")?;
    let html = render_index(raw, csrf);
    Some(
        Response::builder()
            .status(StatusCode::OK)
            .header("content-type", "text/html; charset=utf-8")
            .header("cache-control", "no-store")
            .header("x-content-type-options", "nosniff")
            // The authority console must never be framed (clickjacking on the
            // approve/revoke surfaces). Loopback-only, so DENY is safe.
            .header("x-frame-options", "DENY")
            .body(Full::new(Bytes::from(html)))
            .unwrap(),
    )
}

/// Try to serve a GET request from the embedded SPA. Returns `None` to let the
/// caller fall through (legacy dashboard for `/`, or 404 otherwise):
///
///   * `None` when no SPA is embedded;
///   * `None` for `/api/*` and `/sse/*` (API routes are matched by their own
///     arms first; an UNKNOWN api/sse path must 404, never serve the SPA);
///   * `Some(index.html)` for EXACTLY `/` and `/index.html` (the only
///     token-bearing document, `no-store`);
///   * `Some(asset)` for an exact embedded-asset hit, with immutable caching for
///     content-hashed `/_app/immutable/*` and `no-cache` for everything else;
///   * `None` for every other path (a missing/unknown path 404s — there is no
///     extensionless fallback to `index.html`).
pub fn serve(path: &str, csrf: &str) -> Option<Response<Full<Bytes>>> {
    if !is_embedded() {
        return None;
    }
    // Defensive: API/SSE prefixes are never SPA assets. Their real routes are
    // matched by literal arms before this is called; an unknown one must 404.
    if path.starts_with("/api/") || path == "/api" || path.starts_with("/sse/") || path == "/sse" {
        return None;
    }

    // The token-bearing index is served on exactly these two paths.
    if path == "/" || path == "/index.html" {
        return serve_index(csrf);
    }

    // Otherwise: an EXACT embedded-asset hit, or 404. No heuristic fallback to
    // index.html, so the token-bearing document is not echoed on an unbounded
    // URL set and no other route's slash/case variant can shadow it.
    let (bytes, ctype) = lookup(path)?;
    // SvelteKit content-hashes `/_app/immutable/*` filenames, so they are safe
    // to cache forever; everything else revalidates.
    let cache = if path.starts_with("/_app/immutable/") {
        "public, max-age=31536000, immutable"
    } else {
        "no-cache"
    };
    Some(ok_bytes(bytes, ctype, cache))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn api_and_sse_paths_never_serve_spa() {
        assert!(serve("/api/grants", "tok").is_none());
        assert!(serve("/sse/grants/abc", "tok").is_none());
    }

    #[test]
    fn no_embed_returns_none() {
        if is_embedded() {
            return; // table populated by a real frontend build; skip
        }
        assert!(serve("/", "tok").is_none());
        assert!(serve("/desk", "tok").is_none());
    }

    #[test]
    fn render_index_templates_csrf_and_leaves_no_placeholder() {
        let raw = b"<meta name=\"ember-csrf-token\" content=\"{{CSRF_TOKEN}}\" />";
        let out = render_index(raw, "REAL-TOKEN-abc");
        assert!(out.contains("REAL-TOKEN-abc"));
        assert!(!out.contains(CSRF_PLACEHOLDER), "placeholder must be replaced");
    }

    // The remaining tests exercise the real embedded table; they are inert (and
    // skip) on a build without a frontend bundle so CI stays green.

    fn first_immutable_js() -> Option<&'static str> {
        SPA_ASSETS
            .iter()
            .map(|(p, _, _)| *p)
            .find(|p| p.starts_with("/_app/immutable/") && p.ends_with(".js"))
    }

    #[test]
    fn embedded_index_is_no_store_with_csrf_and_no_etag() {
        if !is_embedded() {
            return;
        }
        let resp = serve("/", "INLINE-CSRF").expect("index served");
        assert_eq!(resp.status(), StatusCode::OK);
        assert_eq!(
            resp.headers().get("content-type").unwrap(),
            "text/html; charset=utf-8"
        );
        // The token-bearing document must NOT be cacheable and must NOT carry an
        // ETag (which would let a same-SHA restart 304 a stale token).
        assert_eq!(resp.headers().get("cache-control").unwrap(), "no-store");
        assert!(resp.headers().get("etag").is_none());
        assert_eq!(resp.headers().get("x-frame-options").unwrap(), "DENY");
    }

    #[test]
    fn embedded_unknown_route_is_404_not_index() {
        if !is_embedded() {
            return;
        }
        // No extensionless fallback: an unknown client route does NOT echo the
        // token-bearing index — it 404s. (Re-open against a known route set when
        // URL-deep-linking lands.)
        assert!(serve("/hold/lease", "csrf").is_none());
        assert!(serve("/index.html/", "csrf").is_none());
        assert!(serve("/metrics/", "csrf").is_none());
    }

    #[test]
    fn embedded_immutable_asset_is_cached_forever() {
        if !is_embedded() {
            return;
        }
        let Some(js) = first_immutable_js() else {
            return;
        };
        let resp = serve(js, "csrf").expect("asset served");
        assert_eq!(resp.status(), StatusCode::OK);
        assert!(resp
            .headers()
            .get("content-type")
            .unwrap()
            .to_str()
            .unwrap()
            .starts_with("text/javascript"));
        assert_eq!(
            resp.headers().get("cache-control").unwrap(),
            "public, max-age=31536000, immutable"
        );
        assert_eq!(resp.headers().get("x-content-type-options").unwrap(), "nosniff");
    }

    #[test]
    fn embedded_missing_concrete_asset_is_404() {
        if !is_embedded() {
            return;
        }
        assert!(serve("/_app/immutable/chunks/ZZZ-nonexistent.js", "c").is_none());
    }

    #[test]
    fn embedded_api_path_never_returns_spa_even_when_embedded() {
        if !is_embedded() {
            return;
        }
        // Keystone: an unknown /api path must 404 via the API not-found path,
        // never leak the SPA index HTML (and its CSRF token).
        assert!(serve("/api/does-not-exist", "c").is_none());
        assert!(serve("/sse/grants/whatever", "c").is_none());
    }
}
