//! Daemon-controlled credential-target allowlist — CRUD over the
//! `credential_bindings` table.
//!
//! META-ARCH-DCC-1-BINDINGS-STORE — foundation subtask of
//! META-ARCH-DAEMON-CONTROLLED-CONFIG. A binding ties a principal
//! (persona UUID) + working-tree (canonical absolute path of a repo
//! root) + remote-name (e.g. `"origin"`) to the remote URL the broker
//! is authorized to inject credentials for. The broker consults this
//! table at request time; the absence of a matching row means the
//! credential target is NOT authorized for the requesting principal.
//!
//! Schema lives in `infra/store.rs::migrate()` under the
//! `credential_bindings_table_schema` checkpoint. The composite primary
//! key `(principal_id, working_tree_id, remote_name)` matches the
//! single-row-get access pattern; the secondary index on
//! `principal_id` covers `list_for_principal`.
//!
//! All five CRUD helpers are free functions over a `&DaemonStore`
//! handle — same shape as `infra/audit.rs::append_audit_event_with_chain`.

use rusqlite::{OptionalExtension, params};

use crate::infra::store::{DaemonStore, StoreError};

/// Composite key identifying a single `credential_bindings` row.
///
/// Used by `get` and `remove` so callers don't have to supply a full
/// `Binding` (which would require knowing `remote_url` and
/// `created_at`) for lookup-by-identity operations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BindingKey {
    /// Persona UUID — the principal authorized to use this binding.
    pub principal_id: String,
    /// Canonical absolute path of the working-tree root.
    pub working_tree_id: String,
    /// Remote name (typically `"origin"`).
    pub remote_name: String,
}

/// A credential-target binding row.
///
/// `created_at` is unix epoch seconds — matches the column's INTEGER
/// type in the schema and is generated by the caller (NOT auto-filled
/// by SQLite) so tests can pin deterministic values.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Binding {
    /// Persona UUID — the principal authorized to use this binding.
    pub principal_id: String,
    /// Canonical absolute path of the working-tree root.
    pub working_tree_id: String,
    /// Remote name (typically `"origin"`).
    pub remote_name: String,
    /// Full remote URL the broker is authorized to inject credentials
    /// for (e.g. `"git@github.com:foo/bar.git"`).
    pub remote_url: String,
    /// Unix epoch seconds at which the binding was created. Provided
    /// by the caller — not auto-filled — so tests pin a deterministic
    /// timestamp and operator-facing audit code can correlate with
    /// other event-stream entries.
    pub created_at: i64,
}

/// Insert a new binding row. Uses `INSERT OR REPLACE` so re-binding
/// the same `(principal, tree, remote)` triple with a new
/// `remote_url` is idempotent rather than a constraint violation —
/// the operator's intent is "this is the current authoritative URL
/// for this binding," not "fail if a row already exists."
pub fn insert(store: &DaemonStore, binding: &Binding) -> Result<(), StoreError> {
    store.conn().execute(
        "INSERT OR REPLACE INTO credential_bindings
            (principal_id, working_tree_id, remote_name, remote_url, created_at)
         VALUES (?1, ?2, ?3, ?4, ?5)",
        params![
            binding.principal_id,
            binding.working_tree_id,
            binding.remote_name,
            binding.remote_url,
            binding.created_at,
        ],
    )?;
    Ok(())
}

/// Fetch a single binding by composite key. Returns `Ok(None)` when
/// no row matches — the broker treats this as "not authorized" rather
/// than an error condition.
pub fn get(store: &DaemonStore, key: &BindingKey) -> Result<Option<Binding>, StoreError> {
    let row = store
        .conn()
        .query_row(
            "SELECT principal_id, working_tree_id, remote_name, remote_url, created_at
             FROM credential_bindings
             WHERE principal_id = ?1 AND working_tree_id = ?2 AND remote_name = ?3",
            params![key.principal_id, key.working_tree_id, key.remote_name],
            |row| {
                Ok(Binding {
                    principal_id: row.get(0)?,
                    working_tree_id: row.get(1)?,
                    remote_name: row.get(2)?,
                    remote_url: row.get(3)?,
                    created_at: row.get(4)?,
                })
            },
        )
        .optional()?;
    Ok(row)
}

/// List every binding owned by `principal_id`. Ordered by
/// `(working_tree_id, remote_name)` so callers iterating over a
/// principal's bindings get a stable, deterministic sequence — useful
/// for diff-based UIs and audit log correlation.
pub fn list_for_principal(
    store: &DaemonStore,
    principal_id: &str,
) -> Result<Vec<Binding>, StoreError> {
    let mut stmt = store.conn().prepare(
        "SELECT principal_id, working_tree_id, remote_name, remote_url, created_at
         FROM credential_bindings
         WHERE principal_id = ?1
         ORDER BY working_tree_id, remote_name",
    )?;
    let rows = stmt
        .query_map(params![principal_id], |row| {
            Ok(Binding {
                principal_id: row.get(0)?,
                working_tree_id: row.get(1)?,
                remote_name: row.get(2)?,
                remote_url: row.get(3)?,
                created_at: row.get(4)?,
            })
        })?
        .collect::<Result<Vec<_>, _>>()?;
    Ok(rows)
}

/// Remove the binding identified by `key`. Returns `Ok(true)` when a
/// row was deleted, `Ok(false)` when no matching row existed — the
/// caller decides whether an absent row is an error or a no-op.
pub fn remove(store: &DaemonStore, key: &BindingKey) -> Result<bool, StoreError> {
    let affected = store.conn().execute(
        "DELETE FROM credential_bindings
         WHERE principal_id = ?1 AND working_tree_id = ?2 AND remote_name = ?3",
        params![key.principal_id, key.working_tree_id, key.remote_name],
    )?;
    Ok(affected > 0)
}

/// Re-root every binding for `principal_id` from `old_path` onto
/// `new_path`. Used when a working-tree moves on disk (e.g. operator
/// renames the parent directory) so the broker's authorization table
/// stays in sync without having to re-issue every binding manually.
/// Returns the number of rows updated.
pub fn move_path(
    store: &DaemonStore,
    principal_id: &str,
    old_path: &str,
    new_path: &str,
) -> Result<usize, StoreError> {
    let affected = store.conn().execute(
        "UPDATE credential_bindings
            SET working_tree_id = ?1
          WHERE principal_id = ?2 AND working_tree_id = ?3",
        params![new_path, principal_id, old_path],
    )?;
    Ok(affected)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_binding() -> Binding {
        Binding {
            principal_id: "00000000-0000-0000-0000-000000000001".to_string(),
            working_tree_id: "/tmp/test-repo".to_string(),
            remote_name: "origin".to_string(),
            remote_url: "git@github.com:foo/bar.git".to_string(),
            created_at: 1234567890,
        }
    }

    fn key_for(binding: &Binding) -> BindingKey {
        BindingKey {
            principal_id: binding.principal_id.clone(),
            working_tree_id: binding.working_tree_id.clone(),
            remote_name: binding.remote_name.clone(),
        }
    }

    /// credential_bindings_insert_get_roundtrip — round-trip a single
    /// binding through `insert` + `get` and assert the URL survives.
    #[test]
    fn credential_bindings_insert_get_roundtrip() {
        let store = DaemonStore::open_in_memory().expect("open");
        let binding = sample_binding();
        insert(&store, &binding).unwrap();
        let key = key_for(&binding);
        let got = get(&store, &key).unwrap().expect("binding");
        assert_eq!(got.remote_url, "git@github.com:foo/bar.git");
        assert_eq!(got.principal_id, binding.principal_id);
        assert_eq!(got.working_tree_id, binding.working_tree_id);
        assert_eq!(got.remote_name, binding.remote_name);
        assert_eq!(got.created_at, binding.created_at);
    }

    /// credential_bindings_get_missing_returns_none — a non-existent
    /// key yields `Ok(None)`, not an error.
    #[test]
    fn credential_bindings_get_missing_returns_none() {
        let store = DaemonStore::open_in_memory().expect("open");
        let key = BindingKey {
            principal_id: "missing".to_string(),
            working_tree_id: "/nowhere".to_string(),
            remote_name: "origin".to_string(),
        };
        assert!(get(&store, &key).unwrap().is_none());
    }

    /// credential_bindings_list_for_principal_returns_matches —
    /// `list_for_principal` returns only rows matching the requested
    /// principal, ordered deterministically.
    #[test]
    fn credential_bindings_list_for_principal_returns_matches() {
        let store = DaemonStore::open_in_memory().expect("open");
        let principal_a = "00000000-0000-0000-0000-0000000000aa";
        let principal_b = "00000000-0000-0000-0000-0000000000bb";

        // Two bindings for principal A (different trees), one for B.
        insert(
            &store,
            &Binding {
                principal_id: principal_a.to_string(),
                working_tree_id: "/tmp/repo-a2".to_string(),
                remote_name: "origin".to_string(),
                remote_url: "git@github.com:org/a2.git".to_string(),
                created_at: 2,
            },
        )
        .unwrap();
        insert(
            &store,
            &Binding {
                principal_id: principal_a.to_string(),
                working_tree_id: "/tmp/repo-a1".to_string(),
                remote_name: "origin".to_string(),
                remote_url: "git@github.com:org/a1.git".to_string(),
                created_at: 1,
            },
        )
        .unwrap();
        insert(
            &store,
            &Binding {
                principal_id: principal_b.to_string(),
                working_tree_id: "/tmp/repo-b".to_string(),
                remote_name: "origin".to_string(),
                remote_url: "git@github.com:org/b.git".to_string(),
                created_at: 3,
            },
        )
        .unwrap();

        let rows = list_for_principal(&store, principal_a).unwrap();
        assert_eq!(rows.len(), 2, "principal A has two bindings");
        // ORDER BY working_tree_id puts /tmp/repo-a1 before /tmp/repo-a2.
        assert_eq!(rows[0].working_tree_id, "/tmp/repo-a1");
        assert_eq!(rows[1].working_tree_id, "/tmp/repo-a2");
        for row in &rows {
            assert_eq!(row.principal_id, principal_a);
        }

        let rows_b = list_for_principal(&store, principal_b).unwrap();
        assert_eq!(rows_b.len(), 1);
        assert_eq!(rows_b[0].remote_url, "git@github.com:org/b.git");
    }

    /// credential_bindings_remove_deletes — `remove` deletes the row
    /// and reports `true`; a second remove reports `false`.
    #[test]
    fn credential_bindings_remove_deletes() {
        let store = DaemonStore::open_in_memory().expect("open");
        let binding = sample_binding();
        insert(&store, &binding).unwrap();
        let key = key_for(&binding);
        assert!(get(&store, &key).unwrap().is_some());

        let first = remove(&store, &key).unwrap();
        assert!(first, "first remove deletes the row");
        assert!(get(&store, &key).unwrap().is_none());

        let second = remove(&store, &key).unwrap();
        assert!(!second, "second remove finds nothing to delete");
    }

    /// credential_bindings_move_path_updates_working_tree_id —
    /// `move_path` rewrites every binding for the principal from
    /// `old_path` to `new_path` and reports the count.
    #[test]
    fn credential_bindings_move_path_updates_working_tree_id() {
        let store = DaemonStore::open_in_memory().expect("open");
        let principal = "00000000-0000-0000-0000-0000000000aa";
        let other_principal = "00000000-0000-0000-0000-0000000000bb";

        // Two bindings under the same path for the target principal
        // (different remote names), plus one for an unrelated principal.
        insert(
            &store,
            &Binding {
                principal_id: principal.to_string(),
                working_tree_id: "/old/path".to_string(),
                remote_name: "origin".to_string(),
                remote_url: "git@github.com:org/repo.git".to_string(),
                created_at: 1,
            },
        )
        .unwrap();
        insert(
            &store,
            &Binding {
                principal_id: principal.to_string(),
                working_tree_id: "/old/path".to_string(),
                remote_name: "upstream".to_string(),
                remote_url: "git@github.com:org/upstream.git".to_string(),
                created_at: 2,
            },
        )
        .unwrap();
        // Unrelated principal at the same path — must NOT be moved.
        insert(
            &store,
            &Binding {
                principal_id: other_principal.to_string(),
                working_tree_id: "/old/path".to_string(),
                remote_name: "origin".to_string(),
                remote_url: "git@github.com:org/other.git".to_string(),
                created_at: 3,
            },
        )
        .unwrap();

        let moved = move_path(&store, principal, "/old/path", "/new/path").unwrap();
        assert_eq!(moved, 2, "only the target principal's two rows move");

        // Target principal: rows live at /new/path.
        let rows = list_for_principal(&store, principal).unwrap();
        assert_eq!(rows.len(), 2);
        for row in &rows {
            assert_eq!(row.working_tree_id, "/new/path");
        }

        // Unrelated principal: untouched.
        let other = list_for_principal(&store, other_principal).unwrap();
        assert_eq!(other.len(), 1);
        assert_eq!(other[0].working_tree_id, "/old/path");
    }
}
